Repository Eco-Mate/EcoMate-Server, pull requests merged in 2023-09, with the labels that each got.

#129 레벨업 기능 추가
  src/main/java/com/greeny/ecomate/auth/service/AuthService.java
  src/main/java/com/greeny/ecomate/challenge/controller/MyChallengeController.java
  src/main/java/com/greeny/ecomate/challenge/repository/MyChallengeRepository.java
  src/main/java/com/greeny/ecomate/challenge/service/MyChallengeService.java
  src/main/java/com/greeny/ecomate/config/SecurityConfig.java
  src/main/java/com/greeny/ecomate/member/controller/LevelController.java
  src/main/java/com/greeny/ecomate/member/dto/CreateLevelRequestDto.java
  src/main/java/com/greeny/ecomate/member/dto/CreateMemberRequestDto.java
  src/main/java/com/greeny/ecomate/member/dto/LevelDto.java
  src/main/java/com/greeny/ecomate/member/dto/MemberDto.java
  src/main/java/com/greeny/ecomate/member/dto/UpdateLevelRequestDto.java
  src/main/java/com/greeny/ecomate/member/entity/Level.java
  src/main/java/com/greeny/ecomate/member/entity/Member.java
  src/main/java/com/greeny/ecomate/member/repository/LevelRepository.java
  src/main/java/com/greeny/ecomate/member/service/LevelService.java
  src/main/java/com/greeny/ecomate/member/service/MemberService.java
Labels: enhancement

#130 사용자 웹소켓 접속 상태 확인 로직 추가, FCM 알림 기능 추가
  .gitignore
  build.gradle
  src/main/java/com/greeny/ecomate/config/SecurityConfig.java
  src/main/java/com/greeny/ecomate/exception/firebase/FirebaseMessageException.java
  src/main/java/com/greeny/ecomate/fcm/FirebaseMessageInitializer.java
  src/main/java/com/greeny/ecomate/fcm/controller/FCMController.java
  src/main/java/com/greeny/ecomate/fcm/dto/CreateFCMTokenDto.java
  src/main/java/com/greeny/ecomate/fcm/service/FCMService.java
  src/main/java/com/greeny/ecomate/member/entity/Member.java
  src/main/java/com/greeny/ecomate/websocket/controller/ChatMessageSendingController.java
  src/main/java/com/greeny/ecomate/websocket/entity/ChatJoin.java
  src/main/java/com/greeny/ecomate/websocket/interceptor/StompAuthInterceptor.java
  src/main/java/com/greeny/ecomate/websocket/listener/WebSocketEventListener.java
  src/main/java/com/greeny/ecomate/websocket/repository/ChatJoinRepository.java
  src/main/java/com/greeny/ecomate/websocket/service/ChatRoomService.java
Labels: enhancement

#131 application.yaml 파일에 firebase 서비스키 파일이름 추가
  src/main/resources/application.yaml
Labels: enhancement

#133 에코매장 기능 추가
  src/main/java/com/greeny/ecomate/config/SecurityConfig.java
  src/main/java/com/greeny/ecomate/map/controller/EcoStoreController.java
  src/main/java/com/greeny/ecomate/map/dto/CreateEcoStoreRequestDto.java
  src/main/java/com/greeny/ecomate/map/dto/EcoStoreDto.java
  src/main/java/com/greeny/ecomate/map/dto/UpdateEcoStoreRequestDto.java
  src/main/java/com/greeny/ecomate/map/entity/EcoStore.java
  src/main/java/com/greeny/ecomate/map/repository/EcoStoreRepository.java
  src/main/java/com/greeny/ecomate/map/service/EcoStoreService.java
  src/main/java/com/greeny/ecomate/member/service/LevelService.java
Labels: enhancement

#135 게시물 검색 기능 추가
  src/main/java/com/greeny/ecomate/board/controller/BoardController.java
  src/main/java/com/greeny/ecomate/board/repository/BoardRepository.java
  src/main/java/com/greeny/ecomate/board/service/BoardService.java
Labels: enhancement

#136 사용자 위치 기준의 에코 매장 조회 기능 추가
  src/main/java/com/greeny/ecomate/map/controller/EcoStoreController.java
  src/main/java/com/greeny/ecomate/map/dto/CreateEcoStoreRequestDto.java
  src/main/java/com/greeny/ecomate/map/dto/EcoStoreDto.java
  src/main/java/com/greeny/ecomate/map/dto/MemberLocationDto.java
  src/main/java/com/greeny/ecomate/map/dto/UpdateEcoStoreRequestDto.java
  src/main/java/com/greeny/ecomate/map/entity/EcoStore.java
  src/main/java/com/greeny/ecomate/map/repository/EcoStoreRepository.java
  src/main/java/com/greeny/ecomate/map/service/EcoStoreService.java
Labels: enhancement

#138 에코매장 좋아요 기능 추가
  src/main/java/com/greeny/ecomate/map/controller/StoreLikeController.java
  src/main/java/com/greeny/ecomate/map/dto/CreateStoreLikeDto.java
  src/main/java/com/greeny/ecomate/map/dto/StoreLikeDto.java
  src/main/java/com/greeny/ecomate/map/entity/EcoStore.java
  src/main/java/com/greeny/ecomate/map/entity/StoreLike.java
  src/main/java/com/greeny/ecomate/map/repository/StoreLikeRepository.java
  src/main/java/com/greeny/ecomate/map/service/StoreLikeService.java
Labels: enhancement

#140 '좋아요'한 에코매장 조회 기능 추가
  src/main/java/com/greeny/ecomate/map/controller/EcoStoreController.java
  src/main/java/com/greeny/ecomate/map/repository/StoreLikeRepository.java
  src/main/java/com/greeny/ecomate/map/service/EcoStoreService.java
Labels: enhancement

#142 에코매장 이미지 업로드 기능 추가
  src/main/java/com/greeny/ecomate/challenge/controller/ChallengeController.java
  src/main/java/com/greeny/ecomate/challenge/dto/ChallengeDto.java
  src/main/java/com/greeny/ecomate/challenge/service/ChallengeService.java
  src/main/java/com/greeny/ecomate/map/controller/EcoStoreController.java
  src/main/java/com/greeny/ecomate/map/dto/EcoStoreDto.java
  src/main/java/com/greeny/ecomate/map/entity/EcoStore.java
  src/main/java/com/greeny/ecomate/map/service/EcoStoreService.java
  src/main/java/com/greeny/ecomate/utils/imageUtil/ImageUtil.java
  src/main/resources/application.yaml
Labels: enhancement

#144 에코매장 전체 조회 기능 추가
  src/main/java/com/greeny/ecomate/map/controller/EcoStoreController.java
  src/main/java/com/greeny/ecomate/map/dto/EcoStoreDto.java
  src/main/java/com/greeny/ecomate/map/service/EcoStoreService.java
Labels: enhancement

#146 채팅방 생성 기능 수정
  src/main/java/com/greeny/ecomate/auth/service/AuthService.java
  src/main/java/com/greeny/ecomate/websocket/service/ChatRoomService.java
Labels: enhancement, fix

#148 레벨 이름 변경
  src/main/java/com/greeny/ecomate/auth/service/AuthService.java
Labels: fix

#150 에코매장 조회 시 사용자의 실시간 위치를 RequestParam으로 받도록 수정
  src/main/java/com/greeny/ecomate/challenge/entity/Challenge.java
  src/main/java/com/greeny/ecomate/map/controller/EcoStoreController.java
  src/main/java/com/greeny/ecomate/map/service/EcoStoreService.java
Labels: enhancement

#151 fcm 전송 오류 시 로그 추가
  src/main/java/com/greeny/ecomate/fcm/service/FCMService.java
Labels: enhancement
