Repository Eco-Mate/EcoMate-Server, pull requests merged in 2023-07, with the labels that each got.

#11 사용자 생성 로직 임시 추가
  src/main/java/com/greeny/ecomate/user/controller/UserController.java
  src/main/java/com/greeny/ecomate/user/dto/CreateUserRequestDto.java
  src/main/java/com/greeny/ecomate/user/entity/Level.java
  src/main/java/com/greeny/ecomate/user/entity/User.java
  src/main/java/com/greeny/ecomate/user/repository/UserRepository.java
  src/main/java/com/greeny/ecomate/user/service/UserService.java
Labels: enhancement

#12 챌린지 기능 추가
  build.gradle
  src/main/java/com/greeny/ecomate/EcoMateApplication.java
  src/main/java/com/greeny/ecomate/challenge/controller/ChallengeController.java
  src/main/java/com/greeny/ecomate/challenge/dto/ChallengeDto.java
  src/main/java/com/greeny/ecomate/challenge/dto/CreateChallengeRequestDto.java
  src/main/java/com/greeny/ecomate/challenge/entity/Challenge.java
  src/main/java/com/greeny/ecomate/challenge/repository/ChallengeRepository.java
  src/main/java/com/greeny/ecomate/challenge/service/ChallengeService.java
  src/main/java/com/greeny/ecomate/config/SwaggerConfig.java
  src/main/java/com/greeny/ecomate/utils/api/ApiUtil.java
  src/main/resources/application.yaml
Labels: enhancement

#15 게시글 CRU 기능 추가
  src/main/java/com/greeny/ecomate/posting/controller/BoardController.java
  src/main/java/com/greeny/ecomate/posting/dto/BoardDto.java
  src/main/java/com/greeny/ecomate/posting/dto/BoardListDto.java
  src/main/java/com/greeny/ecomate/posting/dto/CreateBoardRequestDto.java
  src/main/java/com/greeny/ecomate/posting/dto/UpdateBoardRequestDto.java
  src/main/java/com/greeny/ecomate/posting/entity/Board.java
  src/main/java/com/greeny/ecomate/posting/repository/BoardRepository.java
  src/main/java/com/greeny/ecomate/posting/service/BoardService.java
  src/main/resources/application.yaml
Labels: enhancement

#17 globalExceptionHandler추가, 성공 응답 변경
  src/main/java/com/greeny/ecomate/exception/NotFoundException.java
  src/main/java/com/greeny/ecomate/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/greeny/ecomate/utils/api/ApiUtil.java
Labels: enhancement

#19 Feat: MethodArgumentNotValidException handler 추가
  src/main/java/com/greeny/ecomate/exception/handler/GlobalExceptionHandler.java
Labels: enhancement

#21 챌린지 도전 기능 추가
  src/main/java/com/greeny/ecomate/EcoMateApplication.java
  src/main/java/com/greeny/ecomate/challenge/controller/ChallengeController.java
  src/main/java/com/greeny/ecomate/challenge/controller/MyChallengeController.java
  src/main/java/com/greeny/ecomate/challenge/dto/ChallengeDto.java
  src/main/java/com/greeny/ecomate/challenge/dto/CreateChallengeRequestDto.java
  src/main/java/com/greeny/ecomate/challenge/dto/CreateMyChallengeRequestDto.java
  src/main/java/com/greeny/ecomate/challenge/dto/MyChallengeDto.java
  src/main/java/com/greeny/ecomate/challenge/entity/Challenge.java
  src/main/java/com/greeny/ecomate/challenge/entity/MyChallenge.java
  src/main/java/com/greeny/ecomate/challenge/repository/ChallengeRepository.java
  src/main/java/com/greeny/ecomate/challenge/repository/MyChallengeRepository.java
  src/main/java/com/greeny/ecomate/challenge/service/ChallengeService.java
  src/main/java/com/greeny/ecomate/challenge/service/MyChallengeService.java
Labels: enhancement

#22 챌린지 상태 별 조회 및 캐운트 기능 및 챌린지 달성 포인트 적립 기능 추가
  src/main/java/com/greeny/ecomate/challenge/controller/ChallengeController.java
  src/main/java/com/greeny/ecomate/challenge/controller/MyChallengeController.java
  src/main/java/com/greeny/ecomate/challenge/dto/MyChallengeDto.java
  src/main/java/com/greeny/ecomate/challenge/entity/MyChallenge.java
  src/main/java/com/greeny/ecomate/challenge/repository/MyChallengeRepository.java
  src/main/java/com/greeny/ecomate/challenge/service/ChallengeService.java
  src/main/java/com/greeny/ecomate/challenge/service/MyChallengeService.java
  src/main/java/com/greeny/ecomate/user/entity/User.java
Labels: enhancement

#26 BoardController에 요청 파라미터 validation 추가
  src/main/java/com/greeny/ecomate/posting/controller/BoardController.java
  src/main/java/com/greeny/ecomate/posting/dto/CreateBoardRequestDto.java
  src/main/java/com/greeny/ecomate/posting/dto/UpdateBoardRequestDto.java
  src/main/java/com/greeny/ecomate/posting/service/BoardService.java
Labels: enhancement

#28 게시물 생성, 조회 시 이미지 업로드 및 조회 기능 추가
  src/main/java/com/greeny/ecomate/posting/controller/BoardController.java
  src/main/java/com/greeny/ecomate/posting/dto/BoardDto.java
  src/main/java/com/greeny/ecomate/posting/dto/CreateBoardRequestDto.java
  src/main/java/com/greeny/ecomate/posting/entity/Board.java
  src/main/java/com/greeny/ecomate/posting/repository/BoardRepository.java
  src/main/java/com/greeny/ecomate/posting/service/BoardService.java
  src/main/java/com/greeny/ecomate/s3/service/AwsS3Service.java
  src/main/resources/application.yaml
Labels: enhancement

#29 Feature/25 board paging
  src/main/java/com/greeny/ecomate/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/greeny/ecomate/posting/controller/BoardController.java
  src/main/java/com/greeny/ecomate/posting/dto/BoardListDto.java
  src/main/java/com/greeny/ecomate/posting/repository/BoardRepository.java
  src/main/java/com/greeny/ecomate/posting/service/BoardService.java
Labels: enhancement

#32 챌린지 및 마이챌린지 기능 수정
  src/main/java/com/greeny/ecomate/challenge/controller/ChallengeController.java
  src/main/java/com/greeny/ecomate/challenge/controller/MyChallengeController.java
  src/main/java/com/greeny/ecomate/challenge/service/ChallengeService.java
  src/main/java/com/greeny/ecomate/challenge/service/MyChallengeService.java
  src/main/resources/application.yaml
Labels: enhancement

#33 Redis 추가
  build.gradle
  src/main/java/com/greeny/ecomate/config/RedisConfig.java
  src/main/java/com/greeny/ecomate/utils/jwt/JWTUtil.java
  src/main/java/com/greeny/ecomate/utils/redis/RedisUtil.java
  src/main/resources/application.yaml
Labels: documentation, enhancement

#35 게시물 댓글 생성, 조회 기능 추가
  src/main/java/com/greeny/ecomate/comment/controller/CommentController.java
  src/main/java/com/greeny/ecomate/comment/dto/CommentDto.java
  src/main/java/com/greeny/ecomate/comment/dto/CommentListDto.java
  src/main/java/com/greeny/ecomate/comment/dto/CreateCommentRequestDto.java
  src/main/java/com/greeny/ecomate/comment/entity/Comment.java
  src/main/java/com/greeny/ecomate/comment/repository/CommentRepository.java
  src/main/java/com/greeny/ecomate/comment/service/CommentService.java
  src/main/java/com/greeny/ecomate/posting/entity/Board.java
  src/main/java/com/greeny/ecomate/posting/entity/Reply.java
Labels: enhancement

#37 Redis 추가
  build.gradle
  src/main/java/com/greeny/ecomate/config/RedisConfig.java
  src/main/java/com/greeny/ecomate/utils/redis/RedisUtil.java
Labels: documentation, enhancement

#41 게시물 전체 조회 API에 user 정보 추가
  src/main/java/com/greeny/ecomate/posting/dto/BoardDto.java
  src/main/java/com/greeny/ecomate/posting/repository/BoardRepository.java
  src/main/java/com/greeny/ecomate/user/entity/User.java
Labels: enhancement

#43 Feature/38 board popular posts
  src/main/java/com/greeny/ecomate/posting/controller/BoardController.java
Labels: fix

#45 게시물 수정 api 스펙 변경
  src/main/java/com/greeny/ecomate/posting/controller/BoardController.java
  src/main/java/com/greeny/ecomate/posting/dto/UpdateBoardRequestDto.java
  src/main/java/com/greeny/ecomate/posting/service/BoardService.java
Labels: refactoring

#47 댓글 api의 uri를 복수형으로 수정
  src/main/java/com/greeny/ecomate/comment/controller/CommentController.java
Labels: fix

#51 api url 변경에 따라 SecurityConfig 수정
  src/main/java/com/greeny/ecomate/config/SecurityConfig.java
Labels: enhancement

#52 사용자 인증에 따른 챌린지 기능 수정
  src/main/java/com/greeny/ecomate/auth/controller/AuthController.java
  src/main/java/com/greeny/ecomate/challenge/controller/ChallengeController.java
  src/main/java/com/greeny/ecomate/challenge/controller/MyChallengeController.java
  src/main/java/com/greeny/ecomate/challenge/repository/MyChallengeRepository.java
  src/main/java/com/greeny/ecomate/challenge/service/ChallengeService.java
  src/main/java/com/greeny/ecomate/challenge/service/MyChallengeService.java
  src/main/java/com/greeny/ecomate/config/SecurityConfig.java
  src/main/java/com/greeny/ecomate/config/WebConfig.java
  src/main/java/com/greeny/ecomate/member/repository/MemberRepository.java
  src/main/java/com/greeny/ecomate/member/service/MemberService.java
  src/main/java/com/greeny/ecomate/security/detail/MemberDetailsService.java
  src/main/java/com/greeny/ecomate/security/filter/JwtAuthenticationFilter.java
Labels: enhancement

#57 redis host 값 파일 위치 변경
  src/main/resources/application.yaml
Labels: fix

#59 swagger-ui에서 form-data 로 테스트 가능하게 수정
  src/main/java/com/greeny/ecomate/auth/controller/AuthController.java
  src/main/java/com/greeny/ecomate/converter/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/greeny/ecomate/posting/controller/BoardController.java
Labels: documentation, fix
