Repository Eco-Mate/EcoMate-Server, pull requests merged in 2023-08, with the labels that each got.

#64 Swagger에서 Token 설정 기능 추가
  src/main/java/com/greeny/ecomate/config/SwaggerConfig.java
Labels: documentation

#65 로그인, 회원가입 데이터 요청 바디 타입 변경
  src/main/java/com/greeny/ecomate/auth/controller/AuthController.java
  src/main/java/com/greeny/ecomate/auth/dto/SignUpForm.java
  src/main/java/com/greeny/ecomate/auth/service/AuthService.java
  src/main/java/com/greeny/ecomate/challenge/controller/ChallengeController.java
  src/main/java/com/greeny/ecomate/config/SecurityConfig.java
  src/main/java/com/greeny/ecomate/config/WebConfig.java
  src/main/java/com/greeny/ecomate/member/dto/CreateMemberRequestDto.java
Labels: enhancement

#66 securityconfig 수정
  src/main/java/com/greeny/ecomate/challenge/controller/ChallengeController.java
  src/main/java/com/greeny/ecomate/challenge/controller/MyChallengeController.java
  src/main/java/com/greeny/ecomate/config/SecurityConfig.java
Labels: enhancement

#67 챌린지 이미지 업로드 기능 추가
  src/main/java/com/greeny/ecomate/challenge/controller/ChallengeController.java
  src/main/java/com/greeny/ecomate/challenge/dto/ChallengeDto.java
  src/main/java/com/greeny/ecomate/challenge/entity/Challenge.java
  src/main/java/com/greeny/ecomate/challenge/service/ChallengeService.java
Labels: enhancement

#68 게시물 삭제, 댓글 삭제 기능 추가
  src/main/java/com/greeny/ecomate/comment/controller/CommentController.java
  src/main/java/com/greeny/ecomate/comment/service/CommentService.java
  src/main/java/com/greeny/ecomate/config/SecurityConfig.java
  src/main/java/com/greeny/ecomate/posting/controller/BoardController.java
  src/main/java/com/greeny/ecomate/posting/service/BoardService.java
Labels: enhancement

#70 로그인 기능 추가에 따른 게시물 api 수정
  src/main/java/com/greeny/ecomate/posting/controller/BoardController.java
  src/main/java/com/greeny/ecomate/posting/dto/CreateBoardRequestDto.java
  src/main/java/com/greeny/ecomate/posting/service/BoardService.java
  src/main/resources/application.yaml
Labels: refactoring

#72 게시물에 좋아요 등록/취소 기능 추가
  src/main/java/com/greeny/ecomate/config/SecurityConfig.java
  src/main/java/com/greeny/ecomate/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/greeny/ecomate/like/controller/LikeController.java
  src/main/java/com/greeny/ecomate/like/dto/CreateLikeDto.java
  src/main/java/com/greeny/ecomate/like/dto/LikeDto.java
  src/main/java/com/greeny/ecomate/like/entity/Like.java
  src/main/java/com/greeny/ecomate/like/repository/LikeRepository.java
  src/main/java/com/greeny/ecomate/like/service/LikeService.java
  src/main/java/com/greeny/ecomate/posting/controller/BoardController.java
  src/main/java/com/greeny/ecomate/posting/dto/BoardDto.java
  src/main/java/com/greeny/ecomate/posting/entity/Board.java
  src/main/java/com/greeny/ecomate/posting/service/BoardService.java
Labels: documentation, enhancement

#74 Refactor/73 comment member info
  src/main/java/com/greeny/ecomate/comment/controller/CommentController.java
  src/main/java/com/greeny/ecomate/comment/dto/CommentDto.java
  src/main/java/com/greeny/ecomate/comment/dto/CreateCommentRequestDto.java
  src/main/java/com/greeny/ecomate/comment/service/CommentService.java
Labels: documentation, refactoring

#75 Fix: 특정 게시물의 댓글 조회 uri 복구
  src/main/java/com/greeny/ecomate/comment/controller/CommentController.java
Labels: fix

#78 채팅방 생성 기능 추가
  build.gradle
  src/main/java/com/greeny/ecomate/config/SecurityConfig.java
  src/main/java/com/greeny/ecomate/config/StompWebSocketConfig.java
  src/main/java/com/greeny/ecomate/websocket/controller/ChatRoomController.java
  src/main/java/com/greeny/ecomate/websocket/dto/ChatRoomResponseDto.java
  src/main/java/com/greeny/ecomate/websocket/dto/CreateChatRoomRequestDto.java
  src/main/java/com/greeny/ecomate/websocket/entity/Chat.java
  src/main/java/com/greeny/ecomate/websocket/entity/ChatJoin.java
  src/main/java/com/greeny/ecomate/websocket/entity/ChatRoom.java
  src/main/java/com/greeny/ecomate/websocket/entity/ChatType.java
  src/main/java/com/greeny/ecomate/websocket/handler/StompErrorHandler.java
  src/main/java/com/greeny/ecomate/websocket/repository/ChatJoinRepository.java
  src/main/java/com/greeny/ecomate/websocket/repository/ChatRoomRepository.java
  src/main/java/com/greeny/ecomate/websocket/service/ChatRoomService.java
Labels: enhancement

#80 채팅방 생성시 초대할 멤버 검색 기능 추가
  .gitignore
  build.gradle
  src/main/java/com/greeny/ecomate/member/repository/MemberRepository.java
  src/main/java/com/greeny/ecomate/websocket/controller/ChatRoomController.java
  src/main/java/com/greeny/ecomate/websocket/service/ChatRoomService.java
Labels: enhancement, refactoring

#82 현재 사용자의 게시물 조회 기능 추가
  src/main/java/com/greeny/ecomate/board/controller/BoardController.java
  src/main/java/com/greeny/ecomate/board/dto/BoardDto.java
  src/main/java/com/greeny/ecomate/board/dto/BoardListDto.java
  src/main/java/com/greeny/ecomate/board/dto/CreateBoardRequestDto.java
  src/main/java/com/greeny/ecomate/board/dto/UpdateBoardRequestDto.java
  src/main/java/com/greeny/ecomate/board/entity/Board.java
  src/main/java/com/greeny/ecomate/board/repository/BoardRepository.java
  src/main/java/com/greeny/ecomate/board/service/BoardService.java
  src/main/java/com/greeny/ecomate/comment/controller/CommentController.java
  src/main/java/com/greeny/ecomate/comment/entity/Comment.java
  src/main/java/com/greeny/ecomate/comment/repository/CommentRepository.java
  src/main/java/com/greeny/ecomate/comment/service/CommentService.java
  src/main/java/com/greeny/ecomate/like/entity/Like.java
  src/main/java/com/greeny/ecomate/like/repository/LikeRepository.java
  src/main/java/com/greeny/ecomate/like/service/LikeService.java
Labels: enhancement

#85 단체 채팅 메시지 전송 기능 추가
  src/main/java/com/greeny/ecomate/config/SecurityConfig.java
  src/main/java/com/greeny/ecomate/config/StompWebSocketConfig.java
  src/main/java/com/greeny/ecomate/exception/UnauthorizedAccessException.java
  src/main/java/com/greeny/ecomate/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/greeny/ecomate/exception/websocket/IllegalWebSocketRequestException.java
  src/main/java/com/greeny/ecomate/websocket/controller/ChatController.java
  src/main/java/com/greeny/ecomate/websocket/controller/ChatMessageSendingController.java
  src/main/java/com/greeny/ecomate/websocket/dto/ChatDto.java
  src/main/java/com/greeny/ecomate/websocket/dto/ChatListDto.java
  src/main/java/com/greeny/ecomate/websocket/dto/CreateChatMessageRequestDto.java
  src/main/java/com/greeny/ecomate/websocket/entity/Chat.java
  src/main/java/com/greeny/ecomate/websocket/interceptor/StompAuthInterceptor.java
  src/main/java/com/greeny/ecomate/websocket/repository/ChatJoinRepository.java
  src/main/java/com/greeny/ecomate/websocket/repository/ChatRepository.java
  src/main/java/com/greeny/ecomate/websocket/service/ChatService.java
Labels: enhancement

#86 사용자 정보 수정 기능, 현재 사용자 정보 조회 기능 추가
  src/main/java/com/greeny/ecomate/auth/dto/SignUpForm.java
  src/main/java/com/greeny/ecomate/auth/service/AuthService.java
  src/main/java/com/greeny/ecomate/board/dto/BoardDto.java
  src/main/java/com/greeny/ecomate/board/service/BoardService.java
  src/main/java/com/greeny/ecomate/config/SecurityConfig.java
  src/main/java/com/greeny/ecomate/member/controller/MemberController.java
  src/main/java/com/greeny/ecomate/member/dto/CreateMemberRequestDto.java
  src/main/java/com/greeny/ecomate/member/dto/MemberDto.java
  src/main/java/com/greeny/ecomate/member/dto/UpdateMemberRequestDto.java
  src/main/java/com/greeny/ecomate/member/entity/Member.java
  src/main/java/com/greeny/ecomate/member/service/MemberService.java
  src/main/java/com/greeny/ecomate/s3/service/AwsS3Service.java
Labels: documentation, enhancement

#88 채팅방 관련 uri 수정 및 리팩토링
  src/main/java/com/greeny/ecomate/config/SecurityConfig.java
  src/main/java/com/greeny/ecomate/websocket/controller/ChatRoomController.java
  src/main/java/com/greeny/ecomate/websocket/service/ChatRoomService.java
Labels: fix, refactoring

#91 채팅방 입장 및 퇴장 메시지 전송 기능 추가
  src/main/java/com/greeny/ecomate/websocket/dto/CreateChatMessageRequestDto.java
  src/main/java/com/greeny/ecomate/websocket/service/ChatService.java
Labels: enhancement

#92 Feature/83 mypage
  src/main/java/com/greeny/ecomate/member/controller/MemberController.java
  src/main/java/com/greeny/ecomate/member/dto/MemberDto.java
  src/main/java/com/greeny/ecomate/member/entity/Member.java
  src/main/java/com/greeny/ecomate/member/service/MemberService.java
Labels: enhancement

#95 마이챌린지 Entity 및 DTO 수정
  src/main/java/com/greeny/ecomate/challenge/dto/MyChallengeDto.java
  src/main/java/com/greeny/ecomate/challenge/entity/MyChallenge.java
Labels: fix

#96 게시물 저장 기능, 저장한 게시물 조회 기능 추가
  src/main/java/com/greeny/ecomate/board/controller/BoardController.java
  src/main/java/com/greeny/ecomate/board/entity/BoardSave.java
  src/main/java/com/greeny/ecomate/board/service/BoardService.java
  src/main/java/com/greeny/ecomate/boardSave/controller/BoardSaveController.java
  src/main/java/com/greeny/ecomate/boardSave/dto/CreateBoardSaveRequestDto.java
  src/main/java/com/greeny/ecomate/boardSave/repository/BoardSaveRepository.java
  src/main/java/com/greeny/ecomate/boardSave/service/BoardSaveService.java
  src/main/java/com/greeny/ecomate/config/SecurityConfig.java
Labels: enhancement

#97 팔로우 기능 추가
  src/main/java/com/greeny/ecomate/config/SecurityConfig.java
  src/main/java/com/greeny/ecomate/member/controller/FollowController.java
  src/main/java/com/greeny/ecomate/member/dto/FollowMemberDto.java
  src/main/java/com/greeny/ecomate/member/entity/Follow.java
  src/main/java/com/greeny/ecomate/member/entity/Member.java
  src/main/java/com/greeny/ecomate/member/repository/FollowRepository.java
  src/main/java/com/greeny/ecomate/member/service/FollowService.java
  src/main/java/com/greeny/ecomate/member/service/MemberService.java
Labels: enhancement

#100 도전하지 않은 챌린지 리스트 조회 기능 추가
  src/main/java/com/greeny/ecomate/challenge/controller/ChallengeController.java
  src/main/java/com/greeny/ecomate/challenge/service/ChallengeService.java
  src/main/java/com/greeny/ecomate/config/SecurityConfig.java
Labels: enhancement

#101 게시물 저장 기능의 응답 수정
  src/main/java/com/greeny/ecomate/boardSave/controller/BoardSaveController.java
  src/main/java/com/greeny/ecomate/boardSave/dto/BoardSaveDto.java
  src/main/java/com/greeny/ecomate/boardSave/service/BoardSaveService.java
Labels: enhancement

#105 게시물 저장 여부 확인하는 기능 추가
  src/main/java/com/greeny/ecomate/boardSave/controller/BoardSaveController.java
  src/main/java/com/greeny/ecomate/boardSave/service/BoardSaveService.java
Labels: enhancement

#106 채팅방 생성 이후 멤버 초대 기능 추가
  src/main/java/com/greeny/ecomate/websocket/controller/ChatRoomController.java
  src/main/java/com/greeny/ecomate/websocket/dto/MemberToChatRoomDto.java
  src/main/java/com/greeny/ecomate/websocket/service/ChatRoomService.java
Labels: enhancement

#107 특정 사용자의 프로필 페이지 조회 기능 추가
  src/main/java/com/greeny/ecomate/challenge/controller/MyChallengeController.java
Labels: enhancement

#109 멤버, 챌린지, 마이챌린지 Swagger API 설명 추가
  src/main/java/com/greeny/ecomate/challenge/controller/ChallengeController.java
  src/main/java/com/greeny/ecomate/challenge/controller/MyChallengeController.java
  src/main/java/com/greeny/ecomate/member/controller/MemberController.java
Labels: documentation

#113 권한에 따른 챌린지 리스트 조회 기능 추가
  src/main/java/com/greeny/ecomate/challenge/controller/ChallengeController.java
  src/main/java/com/greeny/ecomate/challenge/repository/ChallengeRepository.java
  src/main/java/com/greeny/ecomate/challenge/service/ChallengeService.java
  src/main/java/com/greeny/ecomate/member/repository/MemberRepository.java
Labels: enhancement

#117 달성하지 않은 챌린지 조회 기능 수정
  src/main/java/com/greeny/ecomate/challenge/controller/ChallengeController.java
  src/main/java/com/greeny/ecomate/challenge/service/ChallengeService.java
Labels: enhancement, fix

#116 채팅방 이름 수정 기능 추가
  src/main/java/com/greeny/ecomate/websocket/controller/ChatRoomController.java
  src/main/java/com/greeny/ecomate/websocket/dto/UpdateChatRoomRequestDto.java
  src/main/java/com/greeny/ecomate/websocket/entity/ChatRoom.java
  src/main/java/com/greeny/ecomate/websocket/repository/ChatJoinRepository.java
  src/main/java/com/greeny/ecomate/websocket/service/ChatRoomService.java
Labels: enhancement

#121 채팅방 나가기 기능 추가
  src/main/java/com/greeny/ecomate/websocket/controller/ChatRoomController.java
  src/main/java/com/greeny/ecomate/websocket/service/ChatRoomService.java
Labels: enhancement

#124 챌린지 등록 게시물과 챌린지 달성 횟수 연동
  src/main/java/com/greeny/ecomate/board/service/BoardService.java
  src/main/java/com/greeny/ecomate/challenge/controller/MyChallengeController.java
  src/main/java/com/greeny/ecomate/challenge/repository/MyChallengeRepository.java
  src/main/java/com/greeny/ecomate/challenge/service/MyChallengeService.java
Labels: enhancement

#125 채팅방 내 멤버들의 챌린지 현황 조회 기능 추가
  src/main/java/com/greeny/ecomate/board/dto/BoardDto.java
  src/main/java/com/greeny/ecomate/board/service/BoardService.java
  src/main/java/com/greeny/ecomate/challenge/repository/MyChallengeRepository.java
  src/main/java/com/greeny/ecomate/utils/imageUtil/ImageUtil.java
  src/main/java/com/greeny/ecomate/websocket/controller/ChatRoomController.java
  src/main/java/com/greeny/ecomate/websocket/dto/ChallengeStatusDto.java
  src/main/java/com/greeny/ecomate/websocket/dto/ChallengeStatusListDto.java
  src/main/java/com/greeny/ecomate/websocket/repository/ChatJoinRepository.java
  src/main/java/com/greeny/ecomate/websocket/service/ChatRoomService.java
Labels: enhancement, refactoring

#127 채팅 메시지 응답에 ChatType 추가
  src/main/java/com/greeny/ecomate/websocket/dto/ChatDto.java
  src/main/java/com/greeny/ecomate/websocket/entity/Chat.java
  src/main/java/com/greeny/ecomate/websocket/repository/ChatJoinRepository.java
  src/main/java/com/greeny/ecomate/websocket/repository/ChatRepository.java
  src/main/java/com/greeny/ecomate/websocket/service/ChatService.java
Labels: enhancement
